name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.3

      - name: Install Dependencies
        run: bun i

      - name: Run ESLint
        run: bun eslint src

      - name: Build & Compile
        run: bun build --verbose
